project:
  type: website
  output-dir: _site

website:
  title: "Programming on the Vlaai"
  description: "A relaxed, friendly space to learn and practice scientific coding at Maastricht University."
  page-navigation: true
  navbar:
    background: "#510702"
    align: center
    logo: images/icoon_vlaai.jpg
    logo-alt: "Programming on the Vlaai logo"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      #- text: "Course"
       # href: course.qmd
  page-footer:
    left: "Programming on the Vlaai · Maastricht University Library"
    right: "Built with [Quarto](https://quarto.org/)."
    background: "#510702"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap

freeze: auto
editor: visual